[package]
name = "yjs-collaboration-server"
version = "0.1.0"
edition = "2021"
description = "High-performance real-time collaborative document editing server built with Yjs CRDT and Volo HTTP"
license = "MIT"
authors = ["KingYen. 1696918097@qq.com"]
repository = "https://github.com/Wenrh2004/yjs-collaboration-server"
homepage = "https://github.com/Wenrh2004/yjs-collaboration-server"
documentation = "https://docs.rs/yjs-collaboration-server"
keywords = [
    "collaboration",
    "crdt",
    "yjs",
    "websocket",
    "volo",
    "rust",
    "volo",
    "volo-http",
]
categories = ["network-programming", "realtime", "asynchronous", "web-server"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# HTTP & RPC framework
volo = "*"
volo-http = { version = "*", features = ["full"] }

# Asynchronous runtime
tokio = { version = "1", features = ["full"] }
futures-util = "0.3.31"

# CRDT synchronization
yrs = "0.23.2"

# Serialization
serde = { version = "1.0", features = ["derive"] }
sonic-rs = "0.5.1"

# Utilities
once_cell = "1.19.0"
uuid = { version = "1.7.0", features = ["v4", "serde"] }
base64 = "0.21.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[profile.release]
opt-level = 3
debug = true
debug-assertions = false
overflow-checks = false
lto = true
panic = 'unwind'
incremental = false
codegen-units = 1
rpath = false
